### ISSUE TITLE
1.19.2 Tetra crash

### ISSUE THREAD

**Issue by CookieStacks** [TinyModularThings/UniqueEnchantments#107]
When I open up the Tetra GUI with any of the UE enchantments in my inventory, the game crashes.

I'm not sure if it can help but here's the portion of the crash report...sorry I don't know what to do about it

java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.CompoundTag.m_128451_(String)" because the return value of "net.minecraft.world.item.ItemStack.m_41783_()" is null
	at uniquebase.handler.EnchantmentHandler.addEnchantmentInfo(EnchantmentHandler.java:222) ~[UniqueEnchantmentsBase-1.19.2-5.0.2.jar%23636!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.item.ItemStack.handler$cjb000$overrideEnchantmentTooltips(ItemStack.java:4618) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:modernfix-common.mixins.json:bugfix.item_cache_flag.ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:relics.mixins.json:ItemStackMixin,pl:mixin:APP:uniquebase.mixins.json:common.item.StackMixin,pl:mixin:APP:uniquebase.mixins.json:client.ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ItemStackMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41709_(ItemStack.java) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:modernfix-common.mixins.json:bugfix.item_cache_flag.ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:relics.mixins.json:ItemStackMixin,pl:mixin:APP:uniquebase.mixins.json:common.item.StackMixin,pl:mixin:APP:uniquebase.mixins.json:client.ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ItemStackMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.world.item.EnchantedBookItem.m_7373_(EnchantedBookItem.java:38) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,xf:fml:apotheosis:ench_info_redirects,re:classloading,xf:fml:apotheosis:ench_info_redirects,pl:mixin:APP:uniquebase.mixins.json:common.item.EnchantedBookMixin,pl:mixin:APP:quark.mixins.json:EnchantedBookItemMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:modernfix-common.mixins.json:bugfix.item_cache_flag.ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:relics.mixins.json:ItemStackMixin,pl:mixin:APP:uniquebase.mixins.json:common.item.StackMixin,pl:mixin:APP:uniquebase.mixins.json:client.ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ItemStackMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinItemStack,pl:mixin:A}
	at se.mickelus.mutil.gui.GuiItem.getTooltipLines(GuiItem.java:117) ~[mutil-1.19.2-5.2.0.jar%23549!/:5.2.0] {re:classloading}
	at se.mickelus.tetra.gui.GuiItemRolling.getTooltipLines(GuiItemRolling.java:61) ~[tetra-1.19.2-5.6.0.jar%23612!/:5.6.0] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] {}
	at se.mickelus.mutil.gui.GuiElement.getTooltipLines(GuiElement.java:370) ~[mutil-1.19.2-5.2.0.jar%23549!/:5.2.0] {re:classloading}
	at se.mickelus.tetra.blocks.workbench.gui.GuiSchematicDetail.getTooltipLines(GuiSchematicDetail.java:223) ~[tetra-1.19.2-5.6.0.jar%23612!/:5.6.0] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] {}
	at se.mickelus.mutil.gui.GuiElement.getTooltipLines(GuiElement.java:370) ~[mutil-1.19.2-5.2.0.jar%23549!/:5.2.0] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] {}
	at se.mickelus.mutil.gui.GuiElement.getTooltipLines(GuiElement.java:370) ~[mutil-1.19.2-5.2.0.jar%23549!/:5.2.0] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] {}
	at se.mickelus.mutil.gui.GuiElement.getTooltipLines(GuiElement.java:370) ~[mutil-1.19.2-5.2.0.jar%23549!/:5.2.0] {re:classloading}
	at se.mickelus.tetra.blocks.workbench.gui.WorkbenchScreen.m_7025_(WorkbenchScreen.java:148) ~[tetra-1.19.2-5.6.0.jar%23612!/:5.6.0] {re:classloading,pl:runtimedistcleaner:A}
	at se.mickelus.tetra.blocks.workbench.gui.WorkbenchScreen.m_6305_(WorkbenchScreen.java:128) ~[tetra-1.19.2-5.6.0.jar%23612!/:5.6.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:441) ~[forge-1.19.2-43.4.0-universal.jar%23668!/:?] {re:mixin,re:classloading,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinForgeHooksClient,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:434) ~[forge-1.19.2-43.4.0-universal.jar%23668!/:?] {re:mixin,re:classloading,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinForgeHooksClient,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.0.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	mutil (mutil), Version: 5.2.0
		Issue tracker URL: https://github.com/mickelus/mutil/issues
		at TRANSFORMER/mutil@5.2.0/se.mickelus.mutil.gui.GuiItem.getTooltipLines(GuiItem.java:117)

	Unique Enchantments Base (uniquebase), Version: 5.0.2
		at TRANSFORMER/uniquebase@5.0.2/uniquebase.handler.EnchantmentHandler.addEnchantmentInfo(EnchantmentHandler.java:222)

	Tetra (tetra), Version: 5.6.0
		Issue tracker URL: https://github.com/mickelus/tetra/issues/new?template=bug_report.md
		at TRANSFORMER/tetra@5.6.0/se.mickelus.tetra.gui.GuiItemRolling.getTooltipLines(GuiItemRolling.java:61)
Stacktrace:
	at uniquebase.handler.EnchantmentHandler.addEnchantmentInfo(EnchantmentHandler.java:222) ~[UniqueEnchantmentsBase-1.19.2-5.0.2.jar%23636!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.item.ItemStack.handler$cjb000$overrideEnchantmentTooltips(ItemStack.java:4618) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:modernfix-common.mixins.json:bugfix.item_cache_flag.ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:relics.mixins.json:ItemStackMixin,pl:mixin:APP:uniquebase.mixins.json:common.item.StackMixin,pl:mixin:APP:uniquebase.mixins.json:client.ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ItemStackMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41709_(ItemStack.java) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:modernfix-common.mixins.json:bugfix.item_cache_flag.ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:relics.mixins.json:ItemStackMixin,pl:mixin:APP:uniquebase.mixins.json:common.item.StackMixin,pl:mixin:APP:uniquebase.mixins.json:client.ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ItemStackMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinItemStack,pl:mixin:A}
	at net.minecraft.world.item.EnchantedBookItem.m_7373_(EnchantedBookItem.java:38) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,xf:fml:apotheosis:ench_info_redirects,re:classloading,xf:fml:apotheosis:ench_info_redirects,pl:mixin:APP:uniquebase.mixins.json:common.item.EnchantedBookMixin,pl:mixin:APP:quark.mixins.json:EnchantedBookItemMixin,pl:mixin:A}
	at net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:modernfix-common.mixins.json:bugfix.item_cache_flag.ItemStackMixin,pl:mixin:APP:apotheosis.mixins.json:ItemStackMixin,pl:mixin:APP:bettercombat.mixins.json:ItemStackMixin,pl:mixin:APP:tetra.mixins.json:MixinItemStack,pl:mixin:APP:placebo.mixins.json:ItemStackMixin,pl:mixin:APP:relics.mixins.json:ItemStackMixin,pl:mixin:APP:uniquebase.mixins.json:common.item.StackMixin,pl:mixin:APP:uniquebase.mixins.json:client.ItemStackMixin,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:APP:mixins.irons_spellbooks.json:ItemStackMixin,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinItemStack,pl:mixin:A}
	at se.mickelus.mutil.gui.GuiItem.getTooltipLines(GuiItem.java:117) ~[mutil-1.19.2-5.2.0.jar%23549!/:5.2.0] {re:classloading}
	at se.mickelus.tetra.gui.GuiItemRolling.getTooltipLines(GuiItemRolling.java:61) ~[tetra-1.19.2-5.6.0.jar%23612!/:5.6.0] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] {}
	at se.mickelus.mutil.gui.GuiElement.getTooltipLines(GuiElement.java:370) ~[mutil-1.19.2-5.2.0.jar%23549!/:5.2.0] {re:classloading}
	at se.mickelus.tetra.blocks.workbench.gui.GuiSchematicDetail.getTooltipLines(GuiSchematicDetail.java:223) ~[tetra-1.19.2-5.6.0.jar%23612!/:5.6.0] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] {}
	at se.mickelus.mutil.gui.GuiElement.getTooltipLines(GuiElement.java:370) ~[mutil-1.19.2-5.2.0.jar%23549!/:5.2.0] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] {}
	at se.mickelus.mutil.gui.GuiElement.getTooltipLines(GuiElement.java:370) ~[mutil-1.19.2-5.2.0.jar%23549!/:5.2.0] {re:classloading}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?] {}
	at se.mickelus.mutil.gui.GuiElement.getTooltipLines(GuiElement.java:370) ~[mutil-1.19.2-5.2.0.jar%23549!/:5.2.0] {re:classloading}
	at se.mickelus.tetra.blocks.workbench.gui.WorkbenchScreen.m_7025_(WorkbenchScreen.java:148) ~[tetra-1.19.2-5.6.0.jar%23612!/:5.6.0] {re:classloading,pl:runtimedistcleaner:A}
	at se.mickelus.tetra.blocks.workbench.gui.WorkbenchScreen.m_6305_(WorkbenchScreen.java:128) ~[tetra-1.19.2-5.6.0.jar%23612!/:5.6.0] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:441) ~[forge-1.19.2-43.4.0-universal.jar%23668!/:?] {re:mixin,re:classloading,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinForgeHooksClient,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:434) ~[forge-1.19.2-43.4.0-universal.jar%23668!/:?] {re:mixin,re:classloading,pl:mixin:APP:enigmaticlegacy.mixins.json:MixinForgeHooksClient,pl:mixin:A}
-- Screen render details --
Details:
	Screen name: se.mickelus.tetra.blocks.workbench.gui.WorkbenchScreen
	Mouse location: Scaled: (337, 156). Absolute: (1013.000000, 470.000000)
	Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.oculus.json:GameRendererAccessor,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer,pl:mixin:APP:mixins.oculus.json:MixinModelViewBobbing,pl:mixin:APP:mixins.oculus.json:MixinTweakFarPlane,pl:mixin:APP:immediatelyfast-common.mixins.json:core.compat.MixinGameRenderer,pl:mixin:APP:immersive_aircraft.mixins.json:client.GameRendererMixin,pl:mixin:APP:mixins.oculus.json:MixinGameRenderer_NightVisionCompat,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.0.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

**Comment by Xaikii** [comment]
First of all, please use a website like pastebin.com for crash logs, or just put the file as an attachment.
But do not just paste the log, we wanna keep everything readable here and not scroll 1 year :)

Next up, this is an issue of Tetra.
ItemStacks should NEVER be null, if you need something to be non-existent they shall use "ItemStack.EMPTY", which would also fix this issue :)

**Comment by CookieStacks** [comment]
hehe sorry, first time using github I'm not used to how y'all do it around here.

Also if you do know it, can you also tell me if I can adjust the ItemStacks value?

**Comment by Xaikii** [comment]
> Also if you do know it, can you also tell me if I can adjust the ItemStacks value?

Unsure what you mean with that, but this issue is something the Developer has to fix. You can not fix it yourself

**Comment by CookieStacks** [comment]
okay thanks I'll try to ask around in Tetra's page

**Comment by matteo335** [comment]
Can be fixed by disabling ItemStackMixin in the configs

**Comment by Xaikii** [comment]
> Can be fixed by disabling ItemStackMixin in the configs

That might make it usable for now, but still doesn't change the fact Tetra is doing bad practices and is at fault here

**Comment by Speiger** [comment]
Closing, because Tetra is doing something Illegal inside minecraft. ItemStacks should never be null.
This is not a UE issue.
